### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by villeheikkila** [yusifsalam/pathfinder_tira#1]
24.11. 17:00:

You could improve the types a bit:

1)

![telegram-cloud-photo-size-4-5902123799258707452-x](https://user-images.githubusercontent.com/39014440/100553794-a899c680-3298-11eb-97df-64a50ed2c947.jpg)

Here you should use the type of React.ChangeEvent<HTMLSelectElement> instead of SyntheticEvent.

2)

![telegram-cloud-photo-size-4-5902123799258707451-x](https://user-images.githubusercontent.com/39014440/100553838-19d97980-3299-11eb-97da-a18c22369865.jpg)

It's a good practise to have exhaustive deps in the useEffects second argument. Add getMaps to the array.

3)

![image](https://user-images.githubusercontent.com/39014440/100553942-e4815b80-3299-11eb-9e5e-d8161f024e3b.png)

Instead of casting the data.maps type to [MapFile] you should type it in the listMaps function like this:

![telegram-cloud-photo-size-4-5902123799258707462-x](https://user-images.githubusercontent.com/39014440/100553987-417d1180-329a-11eb-8270-927246ba3063.jpg)

29.11. 23:26

4)

![image](https://user-images.githubusercontent.com/39014440/100554015-91f46f00-329a-11eb-870d-7770adcb0b0a.png)
 
There's no need to use the non-null assertion operators here.

All in all, excellent project! Algos seem great! Top notch UI.

**Comment by yusifsalam** [comment]
Thanks 🙂
